Add WIP Dockerfile for urllib3 hotfix (#195)
* Add WIP Dockerfile for urllib3 hotfix

A couple things happening here, but to summarize:

- See https://github.com/readthedocs/readthedocs.org/issues/10290 for
  more background
- The bug exists because pyenv compiled Python was built against an old
  openssl package. This is outside our control
- The intended fix is to rebuild the image with pyenv images that have
  hopefully been compiled against openssl 1.1.1+
- This PR doesn't yet resolve the bug, as it doesn't seem pyenv packages
  have indeed been updated recently.
- We probably need to also update the version numbers for all of the
  pyenv installed binaries for this approach to work

To test / repro (after rebuilding this image):

    docker run readthedocs/build:6.0.4 /bin/bash
    docs@778c7ce0877f:/$ eval "$(pyenv init -)"
    docs@778c7ce0877f:/$ pyenv shell 3.7.9
    docs@778c7ce0877f:/$ pip install --quiet requests
    WARNING: You are using pip version 20.0.1; however, version 23.1.2 is available.
    You should consider upgrading via the '/home/docs/.pyenv/versions/3.7.9/bin/python3.7 -m pip install --upgrade pip' command.
    docs@778c7ce0877f:/$ python -m requests
    Traceback (most recent call last):
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 142, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
        import urllib3
      File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
        "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
    ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168

* Install `libssl-dev` and then `node`

When installing `libssl-dev` APT uninstalls `node`. So, we install the required
SSL version first, we compile all the Python versions with that SSL version and
finally we install `node` (which downgrades SSL version again to what it was before)

---------

Co-authored-by: Manuel Kaufmann <humitos@gmail.com>